#define MAINPREFIX z
#define PREFIX jc
#define PREFIX_LONG JaegerCo

#include "script_version.hpp"
#define REQUIRED_VERSION MAJOR.MINOR.PATCH

#define AUTHOR "Jaeger Team"

#ifndef COMPONENT_BEAUTIFIED
    #define COMPONENT_BEAUTIFIED COMPONENT
#endif
#ifdef SUBCOMPONENT_BEAUTIFIED
    #define COMPONENT_NAME QUOTE(Jaeger - COMPONENT_BEAUTIFIED - SUBCOMPONENT_BEAUTIFIED)
#else
    #define COMPONENT_NAME QUOTE(Jaeger - COMPONENT_BEAUTIFIED)
#endif