class SensorTemplatePassiveRadar;
class SensorTemplateActiveRadar;
class SensorTemplateIR;
class SensorTemplateVisual;
class SensorTemplateLaser;
class SensorTemplateNV;
class DefaultVehicleSystemsDisplayManagerLeft{};
class DefaultVehicleSystemsDisplayManagerRight{};
class VehicleSystemsTemplateLeftPilot : DefaultVehicleSystemsDisplayManagerLeft{};
class VehicleSystemsTemplateRightPilot : DefaultVehicleSystemsDisplayManagerRight{};
