[stringtables.usage]
options.ignore = [
    "STR_ACE_Medical_Damage_Impalement",
    "STR_ACE_Medical_Damage_Impalement_Large",
    "STR_ACE_Medical_Damage_Impalement_Medium",
    "STR_ACE_Medical_Damage_Impalement_Minor",
]
