name = "Jaeger Company - Unit Auxiliary"
prefix = "jc"
mainprefix = "ik"
author = "Jaeger Team"
url = "https://discord.gg/FqY9cNzB5n"

[files]
include = [
    "LICENSE",
    "changelog",
    "README",
]

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[hemtt.release]
sign = false
archive = true

[hemtt.launch.default]
presets = [
    "Modding", # .html presets from .hemtt/presets/
]
parameters = [
    "-skipIntro",           # These parameters are passed to the Arma 3 executable
    "-noSplash",            # They do not need to be added to your list
    "-showScriptErrors",    # You can add additional parameters here
    "-debug",
]