name = "Jaeger Company - Unit Auxiliary"
prefix = "jc"
mainprefix = "ik"
author = "Jaeger Team"
url = "https://discord.gg/FqY9cNzB5n"

[files]
include = [
    "LICENSE",
    "changelog",
    "README",
    "addons/MaglockM.pbo",
]
exclude = [
    "addons/main/logos/pngs/*.png",
    "addons/optre_aux/data/elites/minor/pngs/*.png",
    "addons/optre_aux/data/elites/major/pngs/*.png",
    "addons/optre_aux/data/elites/officer/pngs/*.png",
    "addons/optre_aux/data/elites/ultra/pngs/*.png",
    "addons/optre_aux/data/elites/zealot/pngs/*.png",
]

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[hemtt.release]
sign = false
archive = true

[hemtt.launch.default]
presets = [
    "Modding", # .html presets from .hemtt/presets/
]
mission = "Elite%20Testing.VR"
