name = "Jaeger Company - Unit Auxiliary"
prefix = "jc"
mainprefix = "ik"
author = "Jaeger Team"
url = "https://discord.gg/FqY9cNzB5n"

[files]
include = [
    "LICENSE",
    "changelog",
    "README",
]

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[hemtt.release]
sign = false
archive = true