#define COMPONENT optre_aux
#define COMPONENT_BEAUTIFIED Operation: TREBUCHETE Auxiliary

#include "\ik\jc\addons\main\script_mod.hpp"

#include "\ik\jc\addons\main\script_macros.hpp"

#define ELITE_VEST(var1,var2,var3) QPATHTOF(data\elites\var1\jc_elite##var1##_vest_##var2##_##var3##_co.paa)
#define ELITE_HEADGEAR(var1,var2) QPATHTOF(data\elites\var1\jc_elite##var1##_headgear_##var2##_co.paa)
#define ZEALOT_HEADGEAR(var1,var2) QPATHTOF(data\elites\zealot\jc_elite##var1##_headgear_##var2##_co.paa)

#define MINOR_ARMOR_HITPOINTS 35
#define MINOR_SHIELD_STRENGTH 212
#define MINOR_SHIELD_CHARGE 1.0
#define MINOR_SHIELD_DELAY 0.10

#define MAJOR_ARMOR_HITPOINTS MINOR_ARMOR_HITPOINTS
#define MAJOR_SHIELD_STRENGTH 273
#define MAJOR_SHIELD_CHARGE 1.0
#define MAJOR_SHIELD_DELAY 0.10

#define OFFICER_ARMOR_HITPOINTS MINOR_ARMOR_HITPOINTS
#define OFFICER_SHIELD_STRENGTH MAJOR_SHIELD_STRENGTH
#define OFFICER_SHIELD_CHARGE MAJOR_SHIELD_CHARGE
#define OFFICER_SHIELD_DELAY MAJOR_SHIELD_DELAY

#define SPECOPS_ARMOR_HITPOINTS MINOR_ARMOR_HITPOINTS
#define SPECOPS_SHIELD_STRENGTH 333
#define SPECOPS_SHIELD_CHARGE 1.0
#define SPECOPS_SHIELD_DELAY 0.10

#define ULTRA_ARMOR_HITPOINTS MINOR_ARMOR_HITPOINTS
#define ULTRA_SHIELD_STRENGTH 363
#define ULTRA_SHIELD_CHARGE 1.0
#define ULTRA_SHIELD_DELAY 0.10

#define ZEALOT_ARMOR_HITPOINTS MINOR_ARMOR_HITPOINTS
#define ZEALOT_SHIELD_STRENGTH 515
#define ZEALOT_SHIELD_CHARGE 1.0
#define ZEALOT_SHIELD_DELAY 0.10

#define SHADOW_ARMOR_HITPOINTS MINOR_ARMOR_HITPOINTS
#define SHADOW_SHIELD_STRENGTH ZEALOT_SHIELD_STRENGTH
#define SHADOW_SHIELD_CHARGE ZEALOT_SHIELD_CHARGE
#define SHADOW_SHIELD_DELAY ZEALOT_SHIELD_DELAY
